eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
   
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
  user-service:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/user/home
  user-service:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/user/register
  user-service:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/user/lists
  user-service:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/user/{userid}
  user-service:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/test
  user-service:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/user/user

